// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inlwctrswpcklgxnrbaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubHdjdHJzd3Bja2xneG5yYmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjg5NTUsImV4cCI6MjA2NzY0NDk1NX0.0It-376jxuqQdeWaerLlQn6XMycdU-6NB39e3Bcd8oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});